# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyOpenWeatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyOpenWeatherApp

  # - Networking
  pod 'Moya', '~> 8.0'
  pod 'ObjectMapper', '~> 2.2'

  # - Code Styling
  pod 'SwiftLint', '~> 0.19'

  # - UI
  #pod 'TPKeyboardAvoiding'
  #pod 'KVNProgress'

  # - Security
  pod 'SwiftKeychainWrapper', '~> 3.0'

  # - Images
  #pod 'Kingfisher'

  # - DI
  #pod 'Swinject'

  # - Testing
  #pod 'OHHTTPStubs'
  #pod 'OHHTTPStubs/Swift'


  target 'MyOpenWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyOpenWeatherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
